import Link from "next/link";
import {
  Shield, Zap, GitBranch, AlertTriangle, CheckCircle2, ArrowRight,
  Lock, Code2, Bug, Globe, Database, Terminal, ChevronDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LandingNav } from "@/components/landing/nav";

const FEATURES = [
  {
    icon: Bug,
    title: "Automated Vulnerability Detection",
    description:
      "Continuously scan your codebase for secrets, SQL injection, CORS issues, missing security headers, and more — all without manual effort.",
  },
  {
    icon: Zap,
    title: "AI Fix Generation",
    description:
      "Each vulnerability comes with a clear explanation, risk assessment, and ready-to-paste prompts for Cursor, Claude Code, or direct code fixes.",
  },
  {
    icon: GitBranch,
    title: "GitHub Integration",
    description:
      "Trigger scans on every push or PR. Get security feedback as part of your development workflow, before code reaches production.",
  },
  {
    icon: Database,
    title: "Supabase & Firebase Security",
    description:
      "Specialized detection for RLS policies, service role key misuse, Firebase insecure rules, and common AI-generated backend mistakes.",
  },
  {
    icon: Lock,
    title: "Security Score Tracking",
    description:
      "Track your project's security posture over time. Visualize improvements, regressions, and progress across your entire portfolio.",
  },
  {
    icon: Terminal,
    title: "MCP-Ready Architecture",
    description:
      "Integrate SequrAI directly into your AI coding environment via MCP. Run scans and get fixes without leaving your editor.",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Connect your project",
    description:
      "Link your GitHub repo, Vercel project, or Supabase instance. Or just paste a URL. We handle the rest.",
  },
  {
    step: "02",
    title: "Automated scan",
    description:
      "Our security engine analyzes your code for vulnerabilities across 10+ security categories.",
  },
  {
    step: "03",
    title: "Receive AI-powered fixes",
    description:
      "Every vulnerability includes a Cursor prompt and Claude Code prompt ready to paste and fix immediately.",
  },
  {
    step: "04",
    title: "Track & maintain security",
    description:
      "Monitor your security score, set up scheduled scans, and get notified of critical issues instantly.",
  },
];

const PLANS = [
  {
    name: "Builder",
    price: "49",
    description: "For solo developers and indie hackers.",
    features: [
      "5 projects",
      "50 scans/month",
      "2 team members",
      "Basic AI fixes",
      "Email notifications",
      "14-day free trial",
    ],
    cta: "Start free trial",
    highlighted: false,
  },
  {
    name: "Studio",
    price: "99",
    description: "For product teams building with AI.",
    features: [
      "20 projects",
      "200 scans/month",
      "10 team members",
      "Full AI Fix Center",
      "Cursor & Claude prompts",
      "Priority support",
      "14-day free trial",
    ],
    cta: "Start free trial",
    highlighted: true,
  },
  {
    name: "Agency",
    price: "299",
    description: "For agencies managing multiple clients.",
    features: [
      "Unlimited projects",
      "Unlimited scans",
      "Unlimited team members",
      "Full AI Fix Center + MCP",
      "GitHub App integration",
      "Custom webhooks",
      "Dedicated support",
      "14-day free trial",
    ],
    cta: "Contact sales",
    highlighted: false,
  },
];

const FAQS = [
  {
    q: "What kind of vulnerabilities does SequrAI detect?",
    a: "SequrAI detects exposed secrets/API keys, SQL injection, XSS, permissive CORS, missing security headers, Supabase RLS issues, Firebase insecure rules, vulnerable dependencies, missing auth guards, and insecure API configurations.",
  },
  {
    q: "Does it work with code generated by Cursor, Claude Code, or Lovable?",
    a: "Yes — SequrAI is specifically designed for AI-generated code, which often contains predictable security issues like hardcoded credentials, missing auth checks, and disabled RLS. We know the patterns these tools produce.",
  },
  {
    q: "How does the AI fix generation work?",
    a: "When a vulnerability is detected, our AI analyzes it and generates a clear explanation, risk assessment, and step-by-step fix. It also generates a ready-to-paste prompt for Cursor or Claude Code so you can fix it in seconds.",
  },
  {
    q: "Is my code stored on your servers?",
    a: "We only store the analysis results (vulnerability metadata, scores, recommendations). We do not store your full source code. For GitHub integrations, we only read the files needed for analysis.",
  },
  {
    q: "Can I use SequrAI via MCP with Cursor?",
    a: "Yes — the Agency plan includes MCP integration. You can trigger scans, get vulnerability data, and generate fix prompts directly from your Cursor chat without leaving the editor.",
  },
  {
    q: "What's included in the 14-day trial?",
    a: "Full access to your chosen plan, no credit card required. After 14 days you can upgrade, downgrade, or cancel — no lock-in.",
  },
];

const STACK_LOGOS = [
  { name: "Cursor", color: "text-blue-400" },
  { name: "Claude Code", color: "text-orange-400" },
  { name: "Lovable", color: "text-pink-400" },
  { name: "Supabase", color: "text-green-400" },
  { name: "Firebase", color: "text-yellow-400" },
  { name: "Vercel", color: "text-foreground" },
  { name: "Replit", color: "text-purple-400" },
  { name: "Bolt", color: "text-cyan-400" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      <LandingNav />

      {/* ─── Hero ──────────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden pt-32 pb-24">
        {/* Grid background */}
        <div className="absolute inset-0 grid-pattern opacity-40" />
        {/* Radial glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[600px] w-[600px] rounded-full bg-primary/5 blur-[120px]" />

        <div className="relative mx-auto max-w-7xl px-6 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-border/50 bg-secondary/50 px-4 py-1.5 text-xs text-muted-foreground mb-8">
            <span className="h-1.5 w-1.5 rounded-full bg-green-500" />
            Now in early access — 14-day free trial, no card required
          </div>

          <h1 className="mx-auto max-w-4xl text-5xl font-bold tracking-tight text-foreground sm:text-6xl lg:text-7xl">
            Your{" "}
            <span className="text-gradient">AI Security Director</span>
            {" "}for AI-built apps
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground leading-relaxed">
            Automated security scanning, vulnerability detection, and AI-powered fix generation — designed for apps built with Cursor, Claude Code, Lovable, Bolt, Supabase, and Firebase.
          </p>

          <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
            <Button size="lg" className="h-11 px-8 text-sm font-medium" asChild>
              <Link href="/signup">
                Start free trial
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button variant="outline" size="lg" className="h-11 px-8 text-sm font-medium" asChild>
              <Link href="#how-it-works">See how it works</Link>
            </Button>
          </div>

          <p className="mt-4 text-xs text-muted-foreground">
            No credit card required · 14-day trial · Cancel anytime
          </p>

          {/* Security score preview */}
          <div className="mx-auto mt-16 max-w-3xl rounded-2xl border border-border/50 bg-card/50 backdrop-blur-sm p-6 text-left">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <div className="h-2 w-2 rounded-full bg-red-500" />
                <div className="h-2 w-2 rounded-full bg-yellow-500" />
                <div className="h-2 w-2 rounded-full bg-green-500" />
              </div>
              <span className="text-xs text-muted-foreground font-mono">sequrai scan — my-app</span>
            </div>
            <div className="space-y-2 font-mono text-sm">
              <p className="text-muted-foreground">$ sequrai scan ./my-ai-app</p>
              <p className="text-green-400">✓ Scanning 847 files...</p>
              <p className="text-yellow-400">⚠ CRITICAL: Supabase service_role key exposed in client code</p>
              <p className="text-yellow-400">⚠ HIGH: CORS wildcard (*) allows any origin</p>
              <p className="text-yellow-400">⚠ CRITICAL: SQL injection via string interpolation (line 42)</p>
              <p className="text-red-400">✗ Security Score: 34/100 — 3 critical issues found</p>
              <p className="text-primary mt-2">→ Run &apos;sequrai fix --cursor&apos; to generate Cursor prompts for all issues</p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Trusted by stack ────────────────────────────────────────────── */}
      <section className="border-y border-border/50 bg-secondary/20 py-10">
        <div className="mx-auto max-w-7xl px-6">
          <p className="mb-6 text-center text-xs font-medium uppercase tracking-wider text-muted-foreground">
            Built for apps created with
          </p>
          <div className="flex flex-wrap items-center justify-center gap-6 md:gap-10">
            {STACK_LOGOS.map((logo) => (
              <span key={logo.name} className={`text-sm font-semibold ${logo.color} opacity-70 hover:opacity-100 transition-opacity`}>
                {logo.name}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Problem ────────────────────────────────────────────────────── */}
      <section className="py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-16 lg:grid-cols-2 lg:gap-24 items-center">
            <div>
              <Badge variant="outline" className="mb-4 text-xs">The problem</Badge>
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                AI writes great code.
                <br />
                <span className="text-muted-foreground">But it ships with blind spots.</span>
              </h2>
              <p className="mt-6 text-muted-foreground leading-relaxed">
                Cursor, Claude Code, and other AI tools build apps at unprecedented speed. But they consistently produce the same security mistakes: exposed API keys, disabled Row Level Security, permissive CORS, missing auth guards, and unparameterized queries.
              </p>
              <p className="mt-4 text-muted-foreground leading-relaxed">
                These aren&apos;t random bugs — they&apos;re systematic patterns in AI-generated code. And most developers don&apos;t catch them until it&apos;s too late.
              </p>
              <div className="mt-8 space-y-3">
                {[
                  "83% of AI-generated apps have at least one critical security flaw",
                  "Exposed credentials are the #1 cause of data breaches in startups",
                  "Average time to detect a breach: 207 days",
                ].map((stat) => (
                  <div key={stat} className="flex items-start gap-3">
                    <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-yellow-500" />
                    <p className="text-sm text-muted-foreground">{stat}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              {[
                { severity: "CRITICAL", title: "SUPABASE_SERVICE_ROLE_KEY exposed in client-side code", file: "lib/supabase.ts:12" },
                { severity: "CRITICAL", title: "SQL injection via string interpolation in user query", file: "api/users/route.ts:34" },
                { severity: "HIGH", title: "CORS wildcard allows requests from any origin", file: "middleware.ts:8" },
                { severity: "HIGH", title: "API route lacks authentication check", file: "api/admin/route.ts:1" },
                { severity: "MEDIUM", title: "Missing Content-Security-Policy header", file: "next.config.ts" },
              ].map((vuln) => (
                <div
                  key={vuln.title}
                  className="flex items-start gap-4 rounded-lg border border-border/50 bg-card/50 p-4"
                >
                  <Badge
                    variant={vuln.severity === "CRITICAL" ? "destructive" : "outline"}
                    className="mt-0.5 shrink-0 text-xs"
                  >
                    {vuln.severity}
                  </Badge>
                  <div>
                    <p className="text-sm font-medium">{vuln.title}</p>
                    <p className="mt-0.5 font-mono text-xs text-muted-foreground">{vuln.file}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─── How it works ───────────────────────────────────────────────── */}
      <section id="how-it-works" className="border-t border-border/50 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="outline" className="mb-4 text-xs">How it works</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Security in minutes, not months
            </h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Connect, scan, fix. SequrAI integrates into your existing workflow without changing how you build.
            </p>
          </div>

          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {HOW_IT_WORKS.map((step) => (
              <div key={step.step} className="relative">
                <div className="mb-4 font-mono text-4xl font-bold text-border">{step.step}</div>
                <h3 className="mb-2 text-base font-semibold">{step.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Features ───────────────────────────────────────────────────── */}
      <section id="features" className="border-t border-border/50 bg-secondary/10 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="outline" className="mb-4 text-xs">Features</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Everything you need to ship secure
            </h2>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((feature) => (
              <Card key={feature.title} className="border-border/50 bg-card/50">
                <CardHeader className="pb-3">
                  <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10">
                    <feature.icon className="h-4.5 w-4.5 text-primary" />
                  </div>
                  <CardTitle className="text-base">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Pricing ────────────────────────────────────────────────────── */}
      <section id="pricing" className="border-t border-border/50 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="outline" className="mb-4 text-xs">Pricing</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Simple, transparent pricing
            </h2>
            <p className="mt-4 text-muted-foreground">
              14-day free trial on all plans. No credit card required.
            </p>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            {PLANS.map((plan) => (
              <div
                key={plan.name}
                className={`relative rounded-xl border p-8 ${
                  plan.highlighted
                    ? "border-primary/50 bg-primary/5 glow-sm"
                    : "border-border/50 bg-card/50"
                }`}
              >
                {plan.highlighted && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                    <Badge className="text-xs">Most popular</Badge>
                  </div>
                )}
                <div className="mb-6">
                  <h3 className="text-lg font-semibold">{plan.name}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{plan.description}</p>
                  <div className="mt-4 flex items-baseline gap-1">
                    <span className="text-4xl font-bold">€{plan.price}</span>
                    <span className="text-muted-foreground">/month</span>
                  </div>
                </div>
                <ul className="mb-8 space-y-3">
                  {plan.features.map((feature) => (
                    <li key={feature} className="flex items-center gap-2.5 text-sm">
                      <CheckCircle2 className="h-4 w-4 shrink-0 text-green-500" />
                      <span className="text-muted-foreground">{feature}</span>
                    </li>
                  ))}
                </ul>
                <Button
                  className="w-full"
                  variant={plan.highlighted ? "default" : "outline"}
                  asChild
                >
                  <Link href="/signup">{plan.cta}</Link>
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── FAQ ────────────────────────────────────────────────────────── */}
      <section id="faq" className="border-t border-border/50 bg-secondary/10 py-24">
        <div className="mx-auto max-w-3xl px-6">
          <div className="mb-16 text-center">
            <Badge variant="outline" className="mb-4 text-xs">FAQ</Badge>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Frequently asked questions
            </h2>
          </div>

          <div className="space-y-4">
            {FAQS.map((faq) => (
              <div key={faq.q} className="rounded-lg border border-border/50 bg-card/50 p-6">
                <h3 className="text-base font-medium flex items-start gap-3">
                  <ChevronDown className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
                  {faq.q}
                </h3>
                <p className="mt-3 pl-7 text-sm text-muted-foreground leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ────────────────────────────────────────────────────────── */}
      <section className="border-t border-border/50 py-24">
        <div className="mx-auto max-w-7xl px-6">
          <div className="relative overflow-hidden rounded-2xl border border-primary/20 bg-primary/5 px-8 py-16 text-center">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 h-px w-1/2 bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <div className="mx-auto max-w-2xl">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Your AI-built app deserves AI-powered security
              </h2>
              <p className="mt-4 text-muted-foreground">
                Join developers who scan their apps before users do. Start your free 14-day trial today.
              </p>
              <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
                <Button size="lg" className="h-11 px-8" asChild>
                  <Link href="/signup">
                    Start free trial — no card needed
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
                <Button variant="ghost" size="lg" className="h-11" asChild>
                  <Link href="/pricing">View all plans</Link>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── Footer ─────────────────────────────────────────────────────── */}
      <footer className="border-t border-border/50 py-12">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
            <div className="flex items-center gap-2">
              <Shield className="h-4 w-4 text-primary" />
              <span className="text-sm font-semibold">SequrAI</span>
            </div>
            <p className="text-xs text-muted-foreground">
              © 2026 SequrAI. AI Security Director for AI-built apps.
            </p>
            <div className="flex gap-6">
              <Link href="/privacy" className="text-xs text-muted-foreground hover:text-foreground transition-colors">Privacy</Link>
              <Link href="/terms" className="text-xs text-muted-foreground hover:text-foreground transition-colors">Terms</Link>
              <Link href="mailto:hi@sequrai.com" className="text-xs text-muted-foreground hover:text-foreground transition-colors">Contact</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
